version: '2'

networks:
  app-tier:

volumes:
  postgres-data:

services:
  Etcd2:
    image: 'bitnami/etcd:latest'
    env_file: etcd/etcd.env
    ports:
      - 2379:2379
      - 2380:2380
    networks: [ app-tier ]
    container_name: etcd2
    volumes:
      - ./certs/etcd:/opt/bitnami/etcd/certs

  patroni:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patroni2
    networks: [ app-tier ]
    ports:
      - "8008:8008"
      - "5432:5432"
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./certs/etcd:/etc/ssl/etcd
    env_file: patroni/patroni.env

  haproxy:
    image: haproxy
    container_name: haproxy2
    networks: [ app-tier ]
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7000:7000"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs/etcd:/etc/ssl/mycerts

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer2
    networks: [ app-tier ]
    ports:
      - "6432:6432"
    depends_on:
      - patroni
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
      - ./certs/etcd:/etc/ssl/mycerts
