version: '2'

networks:
  app-tier:

volumes:
  postgres-data:

services:
  patroni:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patroni1
    networks: [ app-tier ]
    ports:
      - "8008:8008"
      - "5432:5432"
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: patroni/patroni.env
